# Generated by Django 3.0.8 on 2020-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200804_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
